version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stream rabbitmq_stream_management &&
             rabbitmq-server"